//  Copyright © 2016 Onegini. All rights reserved.

extern NSString *const OGCDVPluginKeyMaxFailureCount;
extern NSString *const OGCDVPluginKeyPin;
extern NSString *const OGCDVPluginKeyPinLength;
extern NSString *const OGCDVPluginKeyProfileId;
extern NSString *const OGCDVPluginKeyRemainingFailureCount;
extern NSString *const OGCDVPluginKeyScopes;
extern NSString *const OGCDVPluginKeyResourceBaseURL;
extern NSString *const OGCDVPluginKeyAuthenticatorType;
extern NSString *const OGCDVPluginKeyAuthenticatorId;
extern NSString *const OGCDVPluginKeyMethod;
extern NSString *const OGCDVPluginKeyType;
extern NSString *const OGCDVPluginKeyMessage;
extern NSString *const OGCDVPluginKeyAuthenticationEvent;
extern NSString *const OGCDVPluginKeyAccept;
extern NSString *const OGCDVPluginKeyPrompt;
extern NSString *const OGCDVPluginKeyErrorCode;
extern NSString *const OGCDVPluginKeyErrorDescription;

extern NSString *const OGCDVPluginClassMobileAuthenticationClient;
extern NSString *const OGCDVPluginClassMobileAuthenticationRequestClient;

extern NSString *const OGCDVPluginAuthenticatorTypePin;
extern NSString *const OGCDVPluginAuthenticatorTypeTouchId;

extern NSString *const OGCDVPluginAuthEventSuccess;
extern NSString *const OGCDVPluginAuthEventPinRequest;
extern NSString *const OGCDVPluginAuthEventCreatePinRequest;
extern NSString *const OGCDVPluginAuthEventFingerprintRequest;

extern NSString *const OGCDVPluginErrDescriptionInternalError;
extern NSString *const OGCDVPluginErrDescriptionIllegalArgumentProfile;
extern NSString *const OGCDVPluginErrDescriptionProfileNotRegistered;
extern NSString *const OGCDVPluginErrDescriptionUserAlreadyAuthenticated;
extern NSString *const OGCDVPluginErrDescriptionNoUserAuthenticated;
extern NSString *const OGCDVPluginErrDescriptionCreatePinNoRegistrationInProgress;
extern NSString *const OGCDVPluginErrDescriptionProvidePinNoAuthenticationInProgress;
extern NSString *const OGCDVPluginErrDescriptionFingerprintNoAuthenticationInProgress;
extern NSString *const OGCDVPluginErrDescriptionIncorrectPin;
extern NSString *const OGCDVPluginErrDescriptionNoSuchAuthenticator;
extern NSString *const OGCDVPluginErrDescriptionNoConfirmationChallenge;
extern NSString *const OGCDVPluginErrDescriptionNoPinChallenge;
extern NSString *const OGCDVPluginErrDescriptionNoFingerprintChallenge;
extern NSString *const OGCDVPluginErrDescriptionInvalidMobileAuthenticationMethod;

extern int const OGCDVPluginErrCodePluginInternalError;
extern int const OGCDVPluginErrCodeConfiguration;
extern int const OGCDVPluginErrCodeIllegalArgument;

extern int const OGCDVPluginErrCodeProfileNotRegistered;
extern int const OGCDVPluginErrCodeUserAlreadyAuthenticated;
extern int const OGCDVPluginErrCodeNoUserAuthenticated;
extern int const OGCDVPluginErrCodeNoSuchAuthenticator;
extern int const OGCDVPluginErrCodeCreatePinNoRegistrationInProgress;
extern int const OGCDVPluginErrCodeProvidePinNoAuthenticationInProgress;
extern int const OGCDVPluginErrCodeFingerprintNoAuthenticationInProgress;
extern int const OGCDVPluginErrCodeNoConfirmationChallenge;
extern int const OGCDVPluginErrCodeNoPinChallenge;
extern int const OGCDVPluginErrCodeNoFingerprintChallenge;
extern int const OGCDVPluginErrCodeInvalidMobileAuthenticationMethod;
extern int const OGCDVPluginErrCodeIoException;
extern int const OGCDVPluginErrCodeIncorrectPin;